functionsDirectory = "/home/node/.openclaw/workspace/deck-director-Sid/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/node/.openclaw/workspace/deck-director-Sid/client/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && cd server && npm install && npm run build && cd ../client && npm install && npm run build"
base = "/home/node/.openclaw/workspace/deck-director-Sid"
functions = "/home/node/.openclaw/workspace/deck-director-Sid/netlify/functions"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
external_node_modules = ["pdfjs-dist"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]