[build]
  base = "."
  command = "npm install && cd server && npm install && npm run build && cd ../client && npm install && npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pdfjs-dist"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "22"
